[package]
name = "baml-star"

[scripts]
pipeline = "--function demo_pipeline"
pipeline_safe = "--function demo_pipeline_safe"
pipeline_markdown = "--function demo_pipeline_markdown"
throws_ok = "--function throws.demo_ok"
throws_error = "--function throws.demo_error"

[generator.python_client]
output_type = "python/pydantic"
output_dir = "python"
naming_convention = "preserve-case"
